/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as TurmasRouteImport } from './routes/turmas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/horarios': typeof HorariosRoute
  '/turmas': typeof TurmasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/horarios': typeof HorariosRoute
  '/turmas': typeof TurmasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/horarios': typeof HorariosRoute
  '/turmas': typeof TurmasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contato' | '/horarios' | '/turmas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contato' | '/horarios' | '/turmas'
  id: '__root__' | '/' | '/contato' | '/horarios' | '/turmas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  HorariosRoute: typeof HorariosRoute
  TurmasRoute: typeof TurmasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  HorariosRoute: HorariosRoute,
  TurmasRoute: TurmasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
